import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import { Suspense } from "react";
import Loading from "./loading";
import NavBar from "@/components/navbar";
import { currentUser } from "@clerk/nextjs/server";



const plusJakartaSans = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function RootLayout({ children }) {

  const user = await currentUser();

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${plusJakartaSans.className}`}>
          <Suspense fallback={<Loading />}>
            <NavBar user={JSON.parse(JSON.stringify(user))} />
            {children}</Suspense>
        </body>
      </html>
    </ClerkProvider>
  );
}


export default RootLayout;